name: FirstWorkflow
on: 
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main    
  workflow_dispatch: 
jobs: 
  build:
    env:
      API_KEY: ${{ secrets.DOGAPIKEY }}
    runs-on: ubuntu-latest
    steps: 
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v
        with:
          node-version: 24       
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7  
        with:
          name: dist-files
          path: 
            dist
      - name: Download Artifacts
        uses: actions/download-artifact@v7
        with: 
          name: dist-files
